### ISSUE TITLE
Muy buen trabajo, Ester!!!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcar-s2-evaluacion-intermedia-EsterGonzalezG#1]
![Super buen trabajo](https://media.giphy.com/media/26uffIRfNMzrTCvok/giphy.gif)

Ahora, para mejorar... qué tal si ponemos mejores nombres de funciones?

![O qué](https://media.giphy.com/media/Nm8ZPAGOwZUQM/giphy.gif)

**Comment by EsterGonzalezG** [comment]
Muchas gracias. Ok me pongo con ello 🙃
